### ISSUE TITLE
Fix Facebook logins/Upgrade Facebook SDK

### ISSUE THREAD

**Issue by aaroncohen73** [osu-cass/pac12#10]
The version of the Facebook SDK that the app used to use was so ancient that it wasn't even available on Packagist anymore. In addition, Facebook has deprecated their old API. ~~All of the Facebook login stuff needs to be rewritten using the new SDK~~

~~Since the Facebook integration on their old website appears to still work, maybe the old Facebook SDK and their old code will work too.~~

I **am** going to have to rewrite things, as it turns out.

**Comment by Kennric** [comment]
I am not sure if they use the facebook features or expect them to work, I'll see if I can find out.
