### ISSUE TITLE
Feature request: change date formats

### ISSUE THREAD

**Issue by Kennric** [osu-cass/pac12#43]
Determine if it is possible/practical to change the date format to M-D-YYYY (allowing single digits without zero padding for month and day)

Particularly for showing the dates of logged workouts, also allow this format for manually entered dates int he calendar widget.

**Comment by aaroncohen73** [comment]
Should it just be changed in specific places (for example, in user-facing form inputs) or everywhere? In theory, all this would require would be changing every instance of 'Y-m-d' to 'n-j-Y'. In practice, I'm not sure what it might break. The first option would make date representation less consistent, but the second option might break more things.

**Comment by Kennric** [comment]
@aaroncohen73 good question. I think they mostly just want to see dates in formats they are familiar with, so really only user-facing things need changed. Can we do that easily without needing to change any stored data?
